name: validate
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  main:
    permissions:
      contents: read # to fetch code (actions/checkout)
    # ignore all-contributors PRs
    if: ${{ !contains(github.head_ref, 'all-contributors') }}
    strategy:
      fail-fast: false
      matrix:
        node: [20, 22, 24]
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: ▶️ Run validate script
        run: npm run validate

      - name: ⬆️ Upload coverage report
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          flags: node-${{ matrix.node }}
          token: ${{ secrets.CODECOV_TOKEN }}
